# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /u/sw/toolchains/gcc-glibc/11.2.0/base/bin/cmake

# The command to remove a file.
RM = /u/sw/toolchains/gcc-glibc/11.2.0/base/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pachy/Desktop/HPCE/nmpde-projects-matrix-free-solvers

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pachy/Desktop/HPCE/nmpde-projects-matrix-free-solvers

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/u/sw/toolchains/gcc-glibc/11.2.0/base/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/u/sw/toolchains/gcc-glibc/11.2.0/base/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pachy/Desktop/HPCE/nmpde-projects-matrix-free-solvers/CMakeFiles /home/pachy/Desktop/HPCE/nmpde-projects-matrix-free-solvers//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pachy/Desktop/HPCE/nmpde-projects-matrix-free-solvers/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MatrixBasedTest

# Build rule for target.
MatrixBasedTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MatrixBasedTest
.PHONY : MatrixBasedTest

# fast build rule for target.
MatrixBasedTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MatrixBasedTest.dir/build.make CMakeFiles/MatrixBasedTest.dir/build
.PHONY : MatrixBasedTest/fast

src/MatrixBasedTest.o: src/MatrixBasedTest.cpp.o
.PHONY : src/MatrixBasedTest.o

# target to build an object file
src/MatrixBasedTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MatrixBasedTest.dir/build.make CMakeFiles/MatrixBasedTest.dir/src/MatrixBasedTest.cpp.o
.PHONY : src/MatrixBasedTest.cpp.o

src/MatrixBasedTest.i: src/MatrixBasedTest.cpp.i
.PHONY : src/MatrixBasedTest.i

# target to preprocess a source file
src/MatrixBasedTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MatrixBasedTest.dir/build.make CMakeFiles/MatrixBasedTest.dir/src/MatrixBasedTest.cpp.i
.PHONY : src/MatrixBasedTest.cpp.i

src/MatrixBasedTest.s: src/MatrixBasedTest.cpp.s
.PHONY : src/MatrixBasedTest.s

# target to generate assembly for a file
src/MatrixBasedTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MatrixBasedTest.dir/build.make CMakeFiles/MatrixBasedTest.dir/src/MatrixBasedTest.cpp.s
.PHONY : src/MatrixBasedTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MatrixBasedTest"
	@echo "... src/MatrixBasedTest.o"
	@echo "... src/MatrixBasedTest.i"
	@echo "... src/MatrixBasedTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

